/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as WalletSetupRouteImport } from './routes/wallet-setup'
import { Route as TokenRouteImport } from './routes/token'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdRouteImport } from './routes/post.$id'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletSetupRoute = WalletSetupRouteImport.update({
  id: '/wallet-setup',
  path: '/wallet-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/post/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NftsRoute: typeof NftsRoute
  RegisterRoute: typeof RegisterRoute
  TokenRoute: typeof TokenRoute
  WalletSetupRoute: typeof WalletSetupRoute
  WriteRoute: typeof WriteRoute
  PostIdRoute: typeof PostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet-setup': {
      id: '/wallet-setup'
      path: '/wallet-setup'
      fullPath: '/wallet-setup'
      preLoaderRoute: typeof WalletSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  NftsRoute: NftsRoute,
  RegisterRoute: RegisterRoute,
  TokenRoute: TokenRoute,
  WalletSetupRoute: WalletSetupRoute,
  WriteRoute: WriteRoute,
  PostIdRoute: PostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
