/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as WalletSetupRouteImport } from './routes/wallet-setup'
import { Route as TokenRouteImport } from './routes/token'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as ProfileAddressRouteImport } from './routes/profile.$address'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletSetupRoute = WalletSetupRouteImport.update({
  id: '/wallet-setup',
  path: '/wallet-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/profile/$address',
  path: '/profile/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/nfts': typeof NftsRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/wallet-setup': typeof WalletSetupRoute
  '/write': typeof WriteRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/marketplace'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$address'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$address'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/marketplace'
    | '/nfts'
    | '/register'
    | '/token'
    | '/wallet-setup'
    | '/write'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$address'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  NftsRoute: typeof NftsRoute
  RegisterRoute: typeof RegisterRoute
  TokenRoute: typeof TokenRoute
  WalletSetupRoute: typeof WalletSetupRoute
  WriteRoute: typeof WriteRoute
  PostIdRoute: typeof PostIdRoute
  ProfileAddressRoute: typeof ProfileAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet-setup': {
      id: '/wallet-setup'
      path: '/wallet-setup'
      fullPath: '/wallet-setup'
      preLoaderRoute: typeof WalletSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/profile/$address': {
      id: '/profile/$address'
      path: '/profile/$address'
      fullPath: '/profile/$address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  NftsRoute: NftsRoute,
  RegisterRoute: RegisterRoute,
  TokenRoute: TokenRoute,
  WalletSetupRoute: WalletSetupRoute,
  WriteRoute: WriteRoute,
  PostIdRoute: PostIdRoute,
  ProfileAddressRoute: ProfileAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
